### ISSUE TITLE
Please transfer any stage >= 1 proposal to tc39

### ISSUE THREAD

**Issue by erights** [jfbastien/papers#35]
See https://github.com/tc39/proposals/issues/44

**Comment by jfbastien** [comment]
I moved the `Math.signbit` proposal to its own repository here: https://github.com/jfbastien/Math.signbit/
and filed for a repository transfer to @bterlson. I'll close the issue as soon as he moves the repo.

**Comment by bterlson** [comment]
@jfbastien done, https://github.com/tc39/proposal-Math.signbit/. You are admin so should be able to add collaborators as you see fit!
