### ISSUE TITLE
D0323r5: what kind of type is the E in unexpected<E>?

### ISSUE THREAD

**Issue by viboes** [jfbastien/papers#43]
Do we want unexpected<E> to be instantiated with functions pointers, pointers, arrays, references, cv-qualified types, void?

IMO, we should allow any unqualified type that is not a reference and is not void.

**Comment by viboes** [comment]
Humm, arrays are not possible, isn't it?

**Comment by jfbastien** [comment]
We should probably allow all the same things `variant` and `optional` allow (assuming they're the same?).
