### ISSUE TITLE
D0323r5: What kind of type can be the T in expected<T,E>

### ISSUE THREAD

**Issue by viboes** [jfbastien/papers#46]
Do we want  immutable expected? 
If yes, should we declare them as `expected<const T, const E>`?
or it is better to have a specific `const_expected<T,E>`?

Do we want so support volatile expected<volatile T,E>? 

Granted we don't want to support references for the first version.

Are there other types we don't want to support?

**Comment by jfbastien** [comment]
What do `optional` and `variant` say here? `const` seems mildly useful, `volatile` doesn't seem useful. I wouldn't spend much text on making either work if it can't just "fall out".

**Comment by viboes** [comment]
Ok. We will do as optional/variant.
