### ISSUE TITLE
D0323r6: Ill formed signatures for expected<void, E>

### ISSUE THREAD

**Issue by viboes** [jfbastien/papers#59]
The following signatures are ill formed or have no sense when `T` `void`.
```
    constexpr const T* operator ->() const;
    constexpr T* operator ->();
    constexpr const T& operator *() const&;
    constexpr T& operator *() &;
    constexpr const T&& operator *() const &&;
    constexpr T&& operator *() &&;
    constexpr const T& value() const&;
    constexpr T& value() &;
    constexpr const T&& value() const &&;
    constexpr T&& value() &&;
    template <class U>
        constexpr T value_or(U&&) const&;
    template <class U>
        constexpr T value_or(U&&) &&;
```
Either all should not participate in overload resolution for `expected<void, E>` or maybe 
`expected<void::E>::value() const`.

I prefer to don't define them for `expected<void, E>`. How to organize the wording then? 
Should we use `see below` for the ill formed parts?

**Comment by jfbastien** [comment]
The paper is published already, issues in the standard should be reported here: https://isocpp.org/std/submit-issue
