### ISSUE TITLE
D0323r6: Do we really want in-place construction for expected<void, E>?

### ISSUE THREAD

**Issue by viboes** [jfbastien/papers#60]
Do we want really to support in-place construction for `expected<void, E>`

    ```c++
        constexpr explicit expected<void, E>::expected(in_place_t);
    ```

as it has no added value respect the default constructor? 

```
expected<void, E> x {in_place};
```

The current wording supports it and is coherent respect to 

```
expected<void, E> x;
x.emplace();
```

**Comment by ecorm** [comment]
I'm in favor of anything that allows the same generic code to handle both `expected<T, E>` and `expected<void, E>` without compile-time branching.

**Comment by jfbastien** [comment]
The paper is published already, issues in the standard should be reported here: https://isocpp.org/std/submit-issue
