### ISSUE TITLE
D0323R9: wrong value category for unexpected(const unexpected<Err>&) constructor

### ISSUE THREAD

**Issue by jwakely** [jfbastien/papers#69]
At https://github.com/jfbastien/papers/blob/fa8426b013c7d026f6ec7fce875cea6aebbf12a4/source/D0323R9.bs#L1414

the _Remarks:_ uses `is_convertible_v<Err, E>` and the _Constraints:_ uses `is_constructible_v<E, Err>` but in both cases it should be `const Err&` not `Err`, since the construction is from a const lvalue not an rvalue.

**Comment by jfbastien** [comment]
Should now be fixed.
