### ISSUE TITLE
N4455: Undefined variable z in sample

### ISSUE THREAD

**Issue by nico-abram** [jfbastien/papers#76]
Is this sample correct?

```cpp

int x = 0;
std::atomic<int> y;
int no() {
  x = 0;
  y.store(0, std::memory_order_release);
  while (!y.load(std::memory_order_acquire));
  x = 1;
  return z;
}

```

(From https://github.com/jfbastien/papers/blob/0ef0303dc7e7d5364a2f36125f83c062981f6876/source/N4455.bs#L376-L388 )

`z` is not defined. I'm not sure if it should be defined and then assigned in the loop or if it should just return 0

**Comment by jfbastien** [comment]
The paper is published already, issues in the standard should be reported here: https://isocpp.org/std/submit-issue
