### ISSUE TITLE
N4455: Incorrect claim about fetch_add(0)

### ISSUE THREAD

**Issue by nico-abram** [jfbastien/papers#77]
As I understand it, the fetch_add is turned into 2 instructions: [mfence and mov](https://godbolt.org/z/eT8MMv1zn)

The text [here](https://github.com/jfbastien/papers/blob/0ef0303dc7e7d5364a2f36125f83c062981f6876/source/N4455.bs#L228-L232) claims it turns into *just* a mov

> This x86 assembly reduces contention by replacing fetch_add—an instruction requiring exclusive cache line access—to a simple movl

**Comment by jfbastien** [comment]
The paper is published already, issues in the standard should be reported here: https://isocpp.org/std/submit-issue
