### ISSUE TITLE
Minor problem in sample code for p0323r11 and p0323r12

### ISSUE THREAD

**Issue by jonitis** [jfbastien/papers#86]
Sample code uses confusing double semicolon at the end of line:
```
ej = unexpected(E());;
ei = unexpected(E());;
```

Also draft R12 of specification still has this problem

**Comment by jonitis** [comment]
One more suspicious thing in section 3.6.
It says `the expected<T, void> vocabularity type means`. Is "vocabularity" here intentional? Or "vocabulary type" was meant instead?

**Comment by jonitis** [comment]
Section 3.7
`In addition std::optional has already be delivered in C++17`. "already be"->"already been"?

**Comment by jonitis** [comment]
Section 3.10
`the use of operator* would be more appropriated.`. "more appropriated"->"more appropriate"?

**Comment by jonitis** [comment]
Section 3.11
`The rational described in`. "rational"->"rationale"?

**Comment by jonitis** [comment]
Hmm. Section name "3.11. Explicit conversion to bool" talks about explicit conversion to bool, but given sample code
`if (expected<char, errc> ch = readNextChar()) {` to my eye looks implicit.

**Comment by jonitis** [comment]
Section 3.13.
Again potentially wrong use of "rational " instead of "rationale ". The document has 3 such uses. The first one is in the beginning of document.

**Comment by jonitis** [comment]
Section 3.14
Again talking about **explicit** conversion to bool, but sample shows implicit conversion:
`if (p) use(*p);`

**Comment by jonitis** [comment]
Section 3.16
`but here the exception throw is given by the user`. "exception throw"->"exception thrown"?

**Comment by jonitis** [comment]
Section 3.17
`// won’t throw` comment is awkwardly placed. Intent is to say that `r.error()` won't throw, not that `getInt()` won't do it.
```
    auto r = getInt(); // won’t throw
    if (!r && r.error() == errc::empty_stream) {
```

**Comment by jonitis** [comment]
Section 3.19
`has the same semantics than optional`. "than"->"as"?

**Comment by jonitis** [comment]
Section 3.20
`C++ does not have concepts yet`. It does now.

**Comment by jonitis** [comment]
Section 3.23
`the semantics and rationale is the same than in [N3672]`. "same than in"->"same as in"?

**Comment by jonitis** [comment]
Section 3.26
`Each operations on expected<T, E> have different requirements and may be disable if T or E doesn’t respect these requirements.`.
"may be disable"->"may be disabled"?

**Comment by jfbastien** [comment]
The paper is already in the standard, issues should go to LWG: https://isocpp.org/std/submit-issue
