### ISSUE TITLE
p0323r7 avoid explicit throw an exception, including bad_access_expected

### ISSUE THREAD

**Issue by raidenluikang** [jfbastien/papers#90]
Is [p0323r7](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0323r7.html) adopted by c++23 ?

std::expected very good candidate for alternative exceptions error-code principle. But there access value methods throw the exception bad_access_expected: again the exception! std::expected already have has_value method to check this situation.

Yes, std::optional::value() also throws exception, but std::expected specially class for exception-free code, in my opinion.

I personally thought about, why can't to remove explicit throwing any exception ?

For example, std::move_only_function's call "empty" state no more throws bad_functional_call exception, it simply cause an UB.

Pls, remove bad_access_expected class, and do not throw an any exception, explicitly! Let value() cause an UB, if there error state.

**Comment by jfbastien** [comment]
Yes it was adopted into C++, so the C++ process is where to send feedback.
