### ISSUE TITLE
volatile deprecation

### ISSUE THREAD

**Issue by d3x0r** [jfbastien/papers#94]
https://github.com/jfbastien/papers/blob/master/source/P1152R3.bs

I'm quite surprised at the amount of acceptance of deprecation of volatile... it's proved to be required since I dunno 2015ish maybe?

These are several usages of volatile, but nothing at all to do with atomic...

https://gist.github.com/d3x0r/a64a923f0d3df6df5129d6cbba74ef64

In order to support no volatile qualified pointers returned from or passed to functions I have to create a different type entirely to assign to the original type; nowhere else in the language do you deliberately convert between two slightly similar versions... maybe it's arguable that conversion to void* is a similar issue... but the 'functionReturn.cc' example in the gist returns a pointer whose value may be subject to change asynchronously from the code execution path... is it not actually proper to return the type as a proper type than assigning it to a specific variable that makes it volatile from a non-volatile type?

Somewhat sorry to bring this directly to you - I started with the implementation... (though I understand now that is's in the wrong overall thread  ... https://github.com/llvm/llvm-project/issues/100038#issuecomment-2495285553   but the issue was about c++'s library complying to such things)  they said 'this isn't the place to discuss committee issues'   so I moved the discussion to https://lists.isocpp.org/std-discussion/2024/11/2729.php  they were unable to offer an alternative, but did end with 'Well, I have good news for you. Volatile isn’t deprecated anymore, they went back on that decision.'  but seems maybe that only the bit applied to compound operators?

But then since this started with you - maybe you have insights?

**Comment by jfbastien** [comment]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1152r0.html has all the uses of volatile listed.
Here's a youtube version https://www.youtube.com/watch?v=KJW_DLaVXIY
Sounds like you're just reading volatile values. That's not deprecated.

**Comment by d3x0r** [comment]
Ya, but in reality you should have started with deprecating volatile in typedefs.

I understand there was a lot of information given, but it was meant as a history to lead up to what the problem is, which is deprecation of volatile pointers returned from and passed to functions.

typedef struct volatile_data volatile *volatile PVDATA; 

now to allocate one of those, I'm using a factory style and have

PVDATA CreateList( void );

PVDATA newList = CreateList();  which has to return a *volatile.... since that's what the target type is.

The other use case for adding/getting data from this takes the address of the volatile and those aren't an issue, but I do have some short-run utility functions that get the count of links (could almost be an inline expression but there's no expression loop construct ).

int GetLinkCount( PVDATA );  // yes, this ends up with a copy of the volatile pointer at that instant.... 

But, because of optimization issues around these types, the typedefs have inherited the volatile, and now there's thousands of deprecated volatile returns for this and various other types like this.  And again things that use these are also often wrapped in critical sections - especially sincd the getlinkcount doesn't do any locking and if left to chance adding a new link to a list could reallocate the list and change the pointer, and release the old data - which is bound to then give random information while GetLinkCount runs... but that's not an issue volatile fixes....

but *volatile returns and arguments also don't break things - yes - there can be some misunderstanding... but C++ can hide it by passing a reference to the volatile pointer; but the code is actually C/C++ and that's not a change that's backwards compatible to C.
